### ISSUE TITLE
Building nstor with NSC fails because of sim.cc

### ISSUE THREAD

**Issue by crud3** [crud3/nstor#1]
@cdoepmann

Building the project with NSC in an Ubuntu 16.04 Docker container fails.

Build fails for version from https://github.com/cdoepmann/nstor/commit/49df172bb90466abbfdacc08208068b2ad1b1174 and subsequently my ported version with ns3.27-ns3.29.

Error:
```
../scratch/01-single-star-web/sim.cc: In function 'bool ParseCmdlineNodeSpec(std::vector<NodeSpecCommand>&, std::__cxx11::string)':
../scratch/01-single-star-web/sim.cc:141:24: error: 'NodeSpecCommand::aspect' is not a class, namespace, or enumeration
       NodeSpecCommand::aspect::RTT,
                        ^
../scratch/01-single-star-web/sim.cc:139:13: error: no match for 'operator=' (operand types are 'NodeSpecCommand' and '<brace-enclosed initializer list>')
     command = {
             ^
../scratch/01-single-star-web/sim.cc:112:8: note: candidate: NodeSpecCommand& NodeSpecCommand::operator=(const NodeSpecCommand&)
 struct NodeSpecCommand {
        ^
../scratch/01-single-star-web/sim.cc:112:8: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'const NodeSpecCommand&'
../scratch/01-single-star-web/sim.cc:112:8: note: candidate: NodeSpecCommand& NodeSpecCommand::operator=(NodeSpecCommand&&)
../scratch/01-single-star-web/sim.cc:112:8: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'NodeSpecCommand&&'
../scratch/01-single-star-web/sim.cc:148:24: error: 'NodeSpecCommand::aspect' is not a class, namespace, or enumeration
       NodeSpecCommand::aspect::RATE,
                        ^
../scratch/01-single-star-web/sim.cc:146:13: error: no match for 'operator=' (operand types are 'NodeSpecCommand' and '<brace-enclosed initializer list>')
     command = {
             ^
../scratch/01-single-star-web/sim.cc:112:8: note: candidate: NodeSpecCommand& NodeSpecCommand::operator=(const NodeSpecCommand&)
 struct NodeSpecCommand {
        ^
../scratch/01-single-star-web/sim.cc:112:8: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'const NodeSpecCommand&'
../scratch/01-single-star-web/sim.cc:112:8: note: candidate: NodeSpecCommand& NodeSpecCommand::operator=(NodeSpecCommand&&)
../scratch/01-single-star-web/sim.cc:112:8: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'NodeSpecCommand&&' 
```

This problem stems from the file `scratch/01-single-star-web/sim.cc`, not from the NSC build itself. After removing the `01-single-star-web/sim.cc` the folder, nstor can be build and the `tor-example` script can be executed with with NSC without errors.

```
git clone https://github.com/crud3/nstor.git && cd nstor && git checkout bump-ns-3.27
rm  -rf scratch/01-single-star-web
RUN ./waf clean ; CXXFLAGS="-Wall" ./waf configure --build-profile=debug --enable-examples --enable-tests --with-nsc=/home/ns3nsc/ns3-nsc/build/ 
CXXFLAGS="-Wall" ./waf
```
The tor-example script can be run with the `--use-nsc` parameter: `time ./waf --run "tor-example --use-nsc=true" | tee tor-example-nsc.txt`

Running with NSC works and gives the following output (shortened):
```
time ./waf --run "tor-example --use-nsc=true" | tee tor-example-nsc.txt
#Output
Waf: Entering directory `/home/ns3nsc/nstor/build'
Waf: Leaving directory `/home/ns3nsc/nstor/build'
Build commands will be stored in build/compile_commands.json
'build' finished successfully (2.053s)
0 0 0 0 0 0 0 
remember 10.1.1.2 -> proxy1
remember 10.1.2.2 -> entry1
remember 10.1.3.2 -> btlnk
remember 10.1.4.2 -> exit1
remember 10.1.5.2 -> proxy2
remember 10.1.6.2 -> entry2
remember 10.1.7.2 -> proxy3
remember 10.1.8.2 -> entry3
remember 10.1.9.2 -> exit2
0.01 0 0 0 0 0 0 

[ ... CUT ... ]

59.99 0 0 323700 127986 373500 147408 

real	0m4.131s
user	0m3.942s
sys	0m0.256s
```

Maybe it's an issue with the gcc version in that container, will look into that.

**Comment by crud3** [comment]
To reproduce error, build the following Dockerfile
https://github.com/crud3/ns3-dce-nsc-experiments/blob/1575f08052b6ce091b7ed86cc2d69e2560006e55/nsc-docker-ubuntu1604/Dockerfile

Tested inside this Docker container with:
- gcc 5.4.0 (default on Ubuntu16.04)
- gcc 6.5.0 (from ppa:ubuntu-toolchain-r/test)
- gcc 7.4.0 (from ppa:ubuntu-toolchain-r/test)

So it's probably not purely a compiler issue
